apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: jkonoor/vproapp:v1
        ports:
          - name: vproapp-port
            containerPort: 8080
      initContainers:
      - name: init-vprodb-service
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup vprodb; do echo waiting for mydb; sleep 2; done"]
      - name: init-vpromemcahche-service
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup vprocache01; do echo waiting for vpromemcache; sleep 2; done"]
  